name: Linter

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on

jobs:
  linter:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout codebase
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          github-token: ${{ env.CI_TOKEN }}

      - name: Run GoLang Linter
        uses: gdcorp-action-public-forks/golangci-lint-action@cc219790cbeccbdecb249751a64f48f25cf356ff #v2.5.3
        with:
          args: --tests=false
          version: latest
          skip-pkg-cache: true
