name: Pull Request Checks

on:
  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}

jobs:
  call-tartufo:
    name: Tartufo Scan
    uses: ./.github/workflows/tartufo.yaml

  call-linter:
    name: Go Linter
    uses: ./.github/workflows/linter.yaml

  call-tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml
