---
name: super-linter

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

# Don't grant any access by default
permissions: {}

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  super-linter:
    name: Super-Linter
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: actions/checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your
          #                             personal access token.
          fetch-depth: 0

      - name: Load super-linter configuration
        run: |
          cat .github/super-linter.env >> "${GITHUB_ENV}"

      - name: super-linter/super-linter
        uses: super-linter/super-linter@4758be622215d0954c8353ee4877ffd60111cf8e  # v6.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
