name: Tartufo

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}

jobs:
  tartufo:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          github-token: ${{ env.CI_TOKEN }}

      - name: Scan with Tartufo
        uses: godaddy/tartufo-action@4.1.0
