name: Tartufo

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}

jobs:
  tartufo:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          github-token: ${{ env.CI_TOKEN }}

      - name: Scan with Tartufo
        uses: godaddy/tartufo-action@4.1.0
