name: Tartufo

on:
  workflow_dispatch:

  workflow_call:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}

jobs:
  tartufo:
    runs-on: [self-hosted, pstore]

    steps:
      - name: Count commits
        id: commits
        run: |
          count=$(jq '.commits | length' $GITHUB_EVENT_PATH)
          echo "count=$count"
          echo "::set-output name=count::${count}"

      - name: actions/checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          fetch-depth: ${{ steps.commits.outputs.count }}

      - name: Run tartufo
        run: |
          python3 -m venv .venv
          . .venv/bin/activate

          pip install --upgrade pip

          pip install tartufo

          echo "scanning branch: ${{ env.target_ref }}"
          tartufo scan-local-repo --branch ${{ env.target_ref }} .
