name: Tests

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: 'github.com/gdcorp-*'

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          github-token: ${{ env.CI_TOKEN }}

      - name: actions/setup-go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: go version
        run: |
          go version
          go env

      - name: go clean --cache
        run: go clean --cache

      - name: go test -race -covermode=atomic
        run: |
          go env
          go test -race -coverprofile=coverage.gcov -covermode=atomic ./...

      - name: jandelgado/gcov2lcov-action
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: coverage.gcov
          outfile: coverage.lcov

      - name: gdcorp-action-public-forks/very_good_coverage
        uses: gdcorp-action-public-forks/very_good_coverage@03275e99cea6981679254681dbdb65b52155b88c # v1.1.1
        with:
          path: coverage.lcov
          min_coverage: 90
